version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - .:/myapp
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - redis
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    links:
      - web:web
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8081:80'
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"

  redis:
    image: redis:4.0-alpine

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - node.name=es
      - cluster.name=cluster
      - discovery.seed_hosts=es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    ports:
      - 5601:5601

  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
    - "1080:1080"
    - "1025:1025"

volumes:
  db_data:
  es:
